version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/app
        ports:
            - "9003:9000"

    nginx:
        image: nginx:stable
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx

    mysql:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: kiloupabocou_db
            MYSQL_ROOT_PASSWORD: "password"

    elasticsearch:
        image: elasticsearch:8.3.1
        container_name: elasticsearch
        networks:
            - es_net
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node

    kibana:
        image: kibana:8.3.2
        container_name: kibana
        networks:
            - es_net
        ports:
            - "5601:5601"

networks:
    es_net:
      driver: bridge
